facet:
  site_name:
    set_default: false
    is_hidden: false
    allowed_sites: {  }
  federated_type:
    is_hidden: false
  federated_terms:
    is_hidden: false
index:
  id: federated_search
  has_site_name_property: true
  username: ''
  password: ''
  has_federated_type_property: true
  has_federated_date_property: true
  has_federated_terms_property: true
content:
  no_results: ''
  search_prompt: ''
  show_empty_search_results: 1
results:
  rows: null
pagination:
  buttons: null
path: /search-app
_core:
  default_config_hash: fC8XjuC9oku1arb2vI5MrVe_wfKdAKGOQFFowpVc6t0
page_title: ''
filter:
  federated_date:
    is_hidden: false
proxy:
  isDisabled: 0
autocomplete:
  isEnabled: 1
  proxy:
    isDisabled: 0
  direct:
    url: ''
  appendWildcard: 1
  use_search_app_creds: 0
  username: ''
  password: ''
  suggestionRows: ''
  numChars: ''
  mode: result
  result:
    titleText: ''
    hideDirectionsText: 0
