module:
  acquia_connector: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  config: 0
  config_filter: 0
  config_inspector: 0
  config_split: 0
  contact: 0
  content_moderation: 0
  contextual: 0
  datetime: 0
  dblog: 0
  demo_umami_content: 0
  dynamic_page_cache: 0
  editor: 0
  federated_styles: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  history: 0
  image: 0
  link: 0
  media: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  quickedit: 0
  rdf: 0
  responsive_image: 0
  rest: 0
  search_api: 0
  search_api_federated_solr: 0
  search_api_field_map: 0
  search_api_solr: 0
  serialization: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  views_ui: 0
  workflows: 0
  menu_link_content: 1
  views: 10
  demo_umami: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  umami: 0
  stark: 0
profile: demo_umami
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
