facet:
  site_name:
    set_default: false
    is_hidden: false
  federated_type:
    is_hidden: false
  federated_terms:
    is_hidden: false
index:
  id: federated_search_index
  has_site_name_property: true
  server_url: 'http://federated-search-demo.local:8983/solr/drupal8/select'
  username: ''
  password: ''
  has_federated_type_property: true
  has_federated_date_property: true
  has_federated_terms_property: true
content:
  no_results: ''
  search_prompt: ''
  show_empty_search_results: 0
results:
  rows: null
pagination:
  buttons: null
path: /search-app
_core:
  default_config_hash: fC8XjuC9oku1arb2vI5MrVe_wfKdAKGOQFFowpVc6t0
page_title: ''
filter:
  federated_date:
    is_hidden: false
autocomplete:
  isEnabled: 1
  url: 'http://d8.fs-demo.local/search-api-federated-solr/search'
  appendWildcard: 0
  suggestionRows: ''
  numChars: ''
  mode: result
  result:
    titleText: ''
    hideDirectionsText: 0
  proxy:
    isDisabled: 0
    url: 'http://d8.fs-demo.local/search-api-federated-solr/search'
  direct:
    url: 'http://federated-search-demo.local:8983/solr/drupal8/select'
  username: ''
  password: ''
proxy:
  url: 'http://d8.fs-demo.local/search-api-federated-solr/search'
  isDisabled: 0
