---
- hosts: all

  vars:
    app_root: "/var/www/federated-search-demo.local"

    web_root: "/var/www/federated-search-demo.local/web"

    solr_conf: "{{ app_root }}/conf/solr"

    sites:
      -
        name: fs-demo-d8
        hostname: d8.fs-demo.local
        database: fs-demo-d8
        docroot: "{{ web_root }}/d8/docroot"
      -
        name: fs-demo-d7
        hostname: d7.fs-demo.local
        database: fs-demo-d7
        docroot: "{{ web_root }}/d7/docroot"
      -
        name: fs-demo-d7-domain-site-one
        hostname: d7-1.fs-demo.local
        database: fs-demo-d7-domain
        docroot: "{{ web_root }}/d7-domain/docroot"
      -
        name: fs-demo-d7-domain-site-two
        hostname: d7-2.fs-demo.local
        database: fs-demo-d7-domain
        docroot: "{{ web_root }}/d7-domain/docroot"
      -
        name: fs-demo-d7-domain-site-three
        hostname: d7-3.fs-demo.local
        database: fs-demo-d7-domain
        docroot: "{{ web_root }}/d7-domain/docroot"
      -
        name: fs-demo-d8-domain-site-one
        hostname: d8-1.fs-demo.local
        database: fs-demo-d8-domain
        docroot: "{{ web_root }}/d8-domain/docroot"
      -
        name: fs-demo-d8-domain-site-two
        hostname: d8-2.fs-demo.local
        database: fs-demo-d8-domain
        docroot: "{{ web_root }}/d8-domain/docroot"
      -
        name: fs-demo-d8-domain-site-three
        hostname: d8-3.fs-demo.local
        database: fs-demo-d8-domain
        docroot: "{{ web_root }}/d8-domain/docroot"

    solr_cores:
      - name: drupal7
        module: search_api_solr-7.x-1.15
        subdir: solr-conf/4.x
      - name: drupal8
        module: search_api_solr-8.x-3.8
        subdir: solr-conf/4.x

  roles:
    - { role: mysql }
    - { role: apache }
    - { role: solr-cors }
    - { role: drush }

