---
- hosts: all

  vars:
    web_root: "/var/www/federated-search-demo.local/web"

    sites:
      -
        name: federated-search-demo
        hostname: federated-search-demo.local
        database: drupal
        docroot: "{{ web_root }}"
      -
        name: federated-search-d7
        hostname: federated-search-demo.d7.local
        database: federated-search-d7
        docroot: "{{ web_root }}/d7/web"
      -
        name: federated-search-demo-domain-site-one
        hostname: federated-search-demo.d8-1.local
        database: drupal
        docroot: "{{ web_root }}"
      -
        name: federated-search-demo-domain-site-two
        hostname: federated-search-demo.d8-2.local
        database: drupal
        docroot: "{{ web_root }}"
      -
        name: federated-search-demo-domain-site-three
        hostname: federated-search-demo.d8-3.local
        database: drupal
        docroot: "{{ web_root }}"

  roles:
    - { role: mysql }
    - { role: apache }
    - { role: solr-cors }
